### ISSUE TITLE
Console being spammed by util/formatNumberLong

### ISSUE THREAD

**Issue by Leidwesen** [PoochyEXE/PoochyEXE.github.io#11]
v0.12.1

[These](https://github.com/PoochyEXE/PoochyEXE.github.io/blob/main/pachinkremental/js/util.js#L302-L304) logs are a bit distracting.

**Comment by PoochyEXE** [comment]
Whoops, that was for local debugging, didn't mean to include that with the commit. Fixed, thanks.
