### ISSUE TITLE
Decimal display bug

### ISSUE THREAD

**Issue by spotky1004** [PoochyEXE/PoochyEXE.github.io#14]
![image](https://user-images.githubusercontent.com/58690998/114571593-c26d0080-9cb1-11eb-9a97-5cd8dbd29d07.png)

**Comment by PoochyEXE** [comment]
Fixed, thanks for the bug report!

(Don't you just love floating point? 14 / 10.0 = 1.4, but 14 * 0.1 =1.4000000000000001. I totally <3.0000000000000004 this sort of thing.)
