### ISSUE TITLE
Scientific notation doesn't work on the slots in the middle of the board in bumper mode for v1.4.0-beta

### ISSUE THREAD

**Issue by QuackQuackBlah** [PoochyEXE/PoochyEXE.github.io#18]
While scientific notation mode shows for the slots at the bottom in the bumper mode, it does not show for the slots in the middle of the board (the numbers on the slots in the middle of the board range from 10 Million to 2 Billion)

**Comment by PoochyEXE** [comment]
Fixed in v1.4.1-beta, thanks for the report!
