### ISSUE TITLE
Point values don't show on wheel immediately after switching from bumpers to basic in v-1.4.1-beta

### ISSUE THREAD

**Issue by QuackQuackBlah** [PoochyEXE/PoochyEXE.github.io#19]
A really small bug, but when switching from bumpers to basic mode, with auto-spin off in basic mode, the point values do not appear on the wheel until after you press spin. 

Edit: It works in both scientific and normal notation (though when you toggle it, the numbers appear, but in the notation that they were in, in other words if you toggle from scientific OFF to scientific ON, the numbers appear on the wheel in scientific OFF mode, though similarly spinning the wheel fixes that)

**Comment by PoochyEXE** [comment]
Fixed in v1.4.2-beta, thanks for the bug report!
