### ISSUE TITLE
The text for upgrading gemstones could be made a wee bit clearer

### ISSUE THREAD

**Issue by QuackQuackBlah** [PoochyEXE/PoochyEXE.github.io#21]
Under the gemstone ball type it states "NOTE: Unlocking one gemstone ball sharply increases the cost of unlocking the others!" While I did figure it out pretty quickly that buying your second gemstone ball also sharply increases the cost of the others, it might be nice to make that a wee bit more explicit with something like "NOTE: For every gemstone ball unlocked the cost of unlocking the others sharply increases!"

**Comment by PoochyEXE** [comment]
Done, I changed "Unlocking one gemstone ball..." to "Each gemstone ball unlocked..." in v1.4.3-beta. Thanks for the suggestion!
