### ISSUE TITLE
Add an option to have pop-up text only for balls that are visible.

### ISSUE THREAD

**Issue by QuackQuackBlah** [PoochyEXE/PoochyEXE.github.io#22]
It'd be nice to have some sort of feature that allows you to only see pop-up text when the ball in question has opacity > 0. In other words, a setting like this would make it so that you don't get pop-up text if you can't see the ball.

Edit another solution, which might be simpler, would be to have more choices for what text pops-up. Like making a distinction between 2-synergy, 3-synergy, and normal gemstones for pop-up text. And also for beachballs from 8-balls.

**Comment by PoochyEXE** [comment]
Added in v1.4.6-beta, thanks for the suggestion!
