### ISSUE TITLE
The Hover-over text can go off the screen in v1.8.0-beta

### ISSUE THREAD

**Issue by QuackQuackBlah** [PoochyEXE/PoochyEXE.github.io#28]
The top row of my upgrades tab is organized like so:
<img width="1005" alt="Screen Shot 2021-06-06 at 8 30 21 AM" src="https://user-images.githubusercontent.com/77398316/120930276-6fa43980-c6a1-11eb-83b4-c6e163925b09.png">

However, when I went to read what the GP system actually does I got this:
<img width="1040" alt="Screen Shot 2021-06-06 at 8 32 22 AM" src="https://user-images.githubusercontent.com/77398316/120930335-b7c35c00-c6a1-11eb-8c43-ca0e0383ebd7.png">

Note that it goes off the screen!

**Comment by PoochyEXE** [comment]
Fixed in v1.8.1-beta, thanks for the bug report!
