### ISSUE TITLE
In v-1.10.0-beta there's a circled 9 in the hover-over text for the perfect freeze upgrade

### ISSUE THREAD

**Issue by QuackQuackBlah** [PoochyEXE/PoochyEXE.github.io#30]
Unclear if this is intentional… 
<img width="280" alt="Screen Shot 2021-06-23 at 7 46 36 AM" src="https://user-images.githubusercontent.com/77398316/123118039-240ac300-d3f7-11eb-9648-74d12ff1c4cc.png">

(really liked this update and how the game is shaping up, by the way)

**Comment by PoochyEXE** [comment]
This one's intentional, it's a reference to the Touhou meme. Normally I'd italicize flavor text, but the ⑨ Unicode character looks distorted and ugly in italics: _⑨_

(Thanks, glad to hear you like it!)
