### ISSUE TITLE
It seems as if only normal balls should count towards ball limit in v.1.11.0-beta

### ISSUE THREAD

**Issue by QuackQuackBlah** [PoochyEXE/PoochyEXE.github.io#32]
The tool-text for gold balls says "don't count towards ball limit" and the text for gemstone balls says "Gemstone balls have the benefits of gold balls". That implies that only normal balls (and maybe beach balls???) should count towards the ball limit, is this the case? Either way, could it be more explicit whether gemstones count towards the ball-limit?

**Comment by PoochyEXE** [comment]
Yes, only normal balls should count towards the limit. I've updated the text in v1.11.1-beta to make it more clear. Thanks for the feedback!
