### ISSUE TITLE
Can't click on drop zone if the page is scrolled

### ISSUE THREAD

**Issue by eliannelavoie** [PoochyEXE/PoochyEXE.github.io#34]
I'm using Firefox 89.0.2 (64-bit) on Linux.

If the page is scrolled, the drop zone stops working.

![Peek 2021-07-07 15-15](https://user-images.githubusercontent.com/13744678/124816362-7212e100-df36-11eb-9372-da71ec76a53a.gif)

The position sent to Board.CanDropAt() is relative to the page, but the method expects position relative to the canvas.

Replacing MouseEvent.pageY by MouseEvent.clientY fixes the problem!

**Comment by PoochyEXE** [comment]
Fixed in v1.11.2-beta. Thanks for bug report, and massive kudos for making it so detailed and even identifying a simple fix!
