### ISSUE TITLE
Add a counter for how many balls have dropped since last reset of hit-rates

### ISSUE THREAD

**Issue by QuackQuackBlah** [PoochyEXE/PoochyEXE.github.io#35]
This would allow for some sort of vague statistical confidence (I think) to be calculated, or at least considered (e.g. once a a hundred thousand balls have been dropped, I trust the figures not to change _too_ much, if more balls drop).

**Comment by PoochyEXE** [comment]
Added in v1.12.1-beta, thanks for the suggestion!
