### ISSUE TITLE
Bonus Wheel text not matching up

### ISSUE THREAD

**Issue by TheHeroBrine422** [PoochyEXE/PoochyEXE.github.io#4]
This seems like some kind of multiplier mismatch between 2 different pieces of text. The bonus wheel on the wheel states on amount of points that will be given, but the text pop up has a higher number. I can't tell which is actually right because my points are so much higher then anything the bonus wheel is giving. For example, one of my point rewards is roughly 9 million, but the text pop up says around 20 billion when it is hit.

Oh and this is occurring in v0.10.0. I didn't notice it until I refreshed to update.

Edit: I think I figured out what is going on now. I don't know if this is intentional but it appears the text on the wheel does not include the multi-wheel upgrade, but the pop up text does. That at least makes sense, but I can't tell if it's what you intended or not.

**Comment by PoochyEXE** [comment]
This is intentional. The wheel displays the base value, while the pop-up text tells you the total value, after factoring in active buffs and the Multi-Spin multiplier. Thanks for taking the time to write up a bug report though!
