### ISSUE TITLE
8-ball & beach ball scoring text does not display when using "Pop-up text: 8-ball+ only"

### ISSUE THREAD

**Issue by Leidwesen** [PoochyEXE/PoochyEXE.github.io#6]
This seems due to a hardcoded text level of 2 being used at https://github.com/PoochyEXE/PoochyEXE.github.io/blob/main/pachinkremental/js/upgrades.js#L615 instead of `text_level`

**Comment by PoochyEXE** [comment]
Fixed in v0.11.1 beta, thanks!
