### ISSUE TITLE
v0.11.0 Beach Ball's spin value is 1/4 that of 8-ball instead of 2x

### ISSUE THREAD

**Issue by Leidwesen** [PoochyEXE/PoochyEXE.github.io#8]
Issue is at https://github.com/PoochyEXE/PoochyEXE.github.io/blob/main/pachinkremental/js/board.js#L141, it only satisfies the beach-ball condition. Should probably be *= 16 like [before](https://github.com/PoochyEXE/PoochyEXE.github.io/commit/7404efe6a45fbe9e1d38cd06f7ffada44b8b3452#diff-6d13a43ab79667a53ab0153036a9c7c40b2896da806832444d4fc0cb335e5bddL145)

**Comment by PoochyEXE** [comment]
Fixed in v0.11.1 beta, thanks!
