### ISSUE TITLE
Scientific Notation.

### ISSUE THREAD

**Issue by TheHeroBrine422** [PoochyEXE/PoochyEXE.github.io#9]
I would like to see scientific notation to be an option for numbers. While letters are ok in my opinion up to a point, past 1e20 or 1e30 they start to lose meaning. I am in the duodecillions and understanding the abbreviation is starting to get hard. It would be so much easier just to read scientific notation. A key for the letters would also be nice.

**Comment by TheHeroBrine422** [comment]
This is probably not a perfect solution, but Antimatter Dimension's number formatter is in a separate file that you probably could figure out how to use. It would give tons of options for formatting. It is also MIT license so no licensing issues. https://github.com/IvarK/IvarK.github.io/blob/master/javascripts/core/format.js

**Comment by mendel3** [comment]
Was about to make an issue to feature request this,  +1

**Comment by James103** [comment]
By the way, scientific notation is already enabled for numbers ≥ 1.00e123. I can confirm because that is just after end-game as of the current version 0.12.0-beta.

**Comment by PoochyEXE** [comment]
Added in v0.12.1, thanks for the suggestion!
